### ISSUE TITLE
No way to download the mod

### ISSUE THREAD

**Issue by Arthur-The-Ok** [Yunatexya/MPTv2ModRE#2]
I already tried every possible download method and none of them worked. I tried using the mod browser, downloading the source code, downloading the release version, copying the link and pasting it on the game, but none worked

![Captura de tela 2023-01-27 124052](https://user-images.githubusercontent.com/81048660/215129040-d9cb5d4e-2fe2-437b-915c-ce3322efc218.png)
Got this when using the mod browser and the github link

![Captura de tela 2023-01-27 124625](https://user-images.githubusercontent.com/81048660/215129357-36867a37-7ab2-43bb-8814-2c40b4bf0709.png)
And this with the downloaded source code

**Comment by Yunatexya** [comment]
Thank you for reporting the issue.
The reason for this issue is that the v0.0.5 release does not contain mod files.

So it has been fixed in version 0.0.7.
